"""The shipped debugging and refactoring templates, run end to end with the scripted agent
(scenarios ACC-29, TPL-14, TPL-19 and TPL-21 of docs/06-scenarios.md). Each workflow is generated by `runner new`
in a scratch repository holding a seeded defect or a small module, given the scripted agent in
place of `claude` (an ordinary edit of the generated file), and driven model-free through `start`,
`approve` and `resume`.

Every test ends with `check_invariants`: every accepted commit is exactly the verified candidate."""

import os
import shutil
import sys
import tomllib
import unittest

from helpers import FAKE_AGENT, EngineCase, done
from test_findings import review

from codesmith import templates

HERE = os.path.dirname(os.path.abspath(__file__))
BRIEFS = os.path.normpath(os.path.join(HERE, "..", "examples", "templates", "briefs"))
PASS = {"answer": review()}

RATIO = 'def ratio(hits, total):\n    """The share of hits; 0.0 for an empty period."""\n    return hits / total\n'
FIXED = ('def ratio(hits, total):\n    """The share of hits; 0.0 for an empty period."""\n'
         '    if total == 0:\n        return 0.0\n    return hits / total\n')
REGRESSION = '''import sys
import unittest

sys.path.insert(0, "src")
import calc  # noqa: E402


class EmptyPeriod(unittest.TestCase):
    def test_the_ratio_of_an_empty_period_is_zero(self):
        self.assertEqual(calc.ratio(0, 0), 0.0)


if __name__ == "__main__":
    unittest.main()
'''
CALC_TEST = '''import sys
import unittest

sys.path.insert(0, "src")
import calc  # noqa: E402


class Ratio(unittest.TestCase):
    def test_half(self):
        self.assertEqual(calc.ratio(1, 2), 0.5)


if __name__ == "__main__":
    unittest.main()
'''


class TemplateRun(EngineCase):
    def generate(self, name, params, out):
        """`runner new NAME` with these parameters, then the generated file edited to use the
        scripted agent, and committed."""
        self.write(".gitignore", "__pycache__/\n")
        shutil.copytree(BRIEFS, os.path.join(self.root, "briefs"))
        self.write("params.toml", "".join(f"{k} = {templates.inline(v)}\n" for k, v in params.items()))
        self.commit()
        self.assertEqual(self.runner("new", name, "-o", os.path.join(self.root, out),
                                     "--params", os.path.join(self.root, "params.toml")), 0, self.output)
        self.wf_path = os.path.join(self.root, out)
        with open(self.wf_path, "rb") as fh:
            doc = tomllib.load(fh)
        doc["defaults"]["agent"] = "fake"
        doc["agents"] = {"fake": {"argv": [sys.executable, FAKE_AGENT],
                                  "read_only_args": ["--read-only"]}}
        with open(self.wf_path, "w", encoding="utf-8") as fh:
            fh.write(templates.dumps(doc))
        self.commit()

    def blob(self, tree, path):
        return self.git_out("rev-parse", f"{tree}:{path}")

    def sign_off(self):
        self.assertEqual(self.start(), 255, self.output)           # waits for the owner
        self.assertEqual(self.runner("approve", "latest", "signoff", "-C", self.root), 0, self.output)
        self.assertEqual(self.resume(), 0, self.output)


class Debugging(TemplateRun):
    TEST_ONE = "python3 -B tests/regression/test_div_zero_17.py"

    def test_debugging_proves_fail_then_pass(self):
        """acc: debugging proves fail-then-pass (ACC-29): reproduce and fix are accepted on two
        candidates; verification.json shows the expected failure on the first and the pass on the
        second, of the same file blob"""
        self.write("src/calc/__init__.py", RATIO)
        self.write("tests/test_calc.py", CALC_TEST)
        self.generate("debugging", {
            "bug": "div-zero-17", "report": "briefs/div-zero-17.md", "symptom": "ZeroDivisionError",
            "area": "src/calc/**", "regression_test": "tests/regression/test_div_zero_17.py",
            "test_one": self.TEST_ONE,
            "suite": "python3 -B tests/test_calc.py && " + self.TEST_ONE,
        }, "debug-17.toml")
        notes = {"write": {"docs/debug/div-zero-17/reproduction.md": "Command, output, input (0, 0).\n",
                           "tests/regression/test_div_zero_17.py": REGRESSION}, "answer": done()}
        self.script({
            "reproduce": [notes],
            "reproduce.review.root-cause-rosa": [PASS],
            "diagnose": [{"write": {"docs/debug/div-zero-17/diagnosis.md":
                                    "Root cause: src/calc/__init__.py:3 divides by total.\n"},
                          "answer": done()}],
            "diagnose.review.root-cause-rosa": [PASS],
            "diagnose.review.principled-priya": [PASS],
            "fix": [{"write": {"src/calc/__init__.py": FIXED}, "answer": done()}],
            "fix.review.root-cause-rosa": [PASS],
            "fix.review.principled-priya": [PASS],
            "siblings": [{"write": {"docs/debug/div-zero-17/siblings.md": "No other site divides.\n"},
                          "answer": done()}],
            "siblings.review.root-cause-rosa": [PASS],
            "siblings.review.principled-priya": [PASS],
        })
        self.sign_off()
        state = self.the_run().state["tasks"]
        self.assertEqual({t: state[t]["status"] for t in ("reproduce", "diagnose", "fix", "siblings")},
                         dict.fromkeys(("reproduce", "diagnose", "fix", "siblings"), "accepted"))
        first, second = state["reproduce"]["candidate"], state["fix"]["candidate"]
        self.assertNotEqual(first, second)
        repro = self.read_json("reproduce", "attempt-1", "verification.json")["results"]
        failing = next(r for r in repro if r.get("expect") == "fail")
        self.assertEqual((failing["result"], failing["fail_pattern"], failing["runs"][0]["result"],
                          failing["candidate"]), ("pass", "ZeroDivisionError", "fail", first))
        fixed = self.read_json("fix", "attempt-1", "verification.json")["results"]
        passing = next(r for r in fixed if r["commands"] == [self.TEST_ONE])
        self.assertEqual((passing["result"], passing["runs"][0]["exit"], passing["candidate"]),
                         ("pass", 0, second))
        self.assertEqual(failing["commands"], [self.TEST_ONE])
        path = "tests/regression/test_div_zero_17.py"
        self.assertEqual(self.blob(first, path), self.blob(second, path))
        self.check_invariants()

    def test_the_regression_test_is_protected_inside_the_area(self):
        """tpl: the regression test stays as reproduced even inside the area (TPL-19): with
        area = "src/**" and the test under src/, a fix and a siblings sweep that weaken it are sent
        back as writing a protected file; the accepted fix leaves its blob unchanged"""
        test_one = "python3 -B src/calc/test_regression.py"
        self.write("src/calc/__init__.py", RATIO)
        self.write("tests/test_calc.py", CALC_TEST)
        self.generate("debugging", {
            "bug": "div-zero-17", "report": "briefs/div-zero-17.md", "symptom": "ZeroDivisionError",
            "area": "src/**", "regression_test": "src/calc/test_regression.py",
            "test_one": test_one, "suite": "python3 -B tests/test_calc.py && " + test_one,
        }, "debug-17.toml")
        weakened = REGRESSION.replace("self.assertEqual(calc.ratio(0, 0), 0.0)", "self.assertTrue(True)")
        self.script({
            "reproduce": [{"write": {"docs/debug/div-zero-17/reproduction.md": "Input (0, 0).\n",
                                     "src/calc/test_regression.py": REGRESSION}, "answer": done()}],
            "reproduce.review.root-cause-rosa": [PASS],
            "diagnose": [{"write": {"docs/debug/div-zero-17/diagnosis.md": "Root cause: line 3.\n"},
                          "answer": done()}],
            "diagnose.review.root-cause-rosa": [PASS],
            "diagnose.review.principled-priya": [PASS],
            "fix": [{"write": {"src/calc/test_regression.py": weakened}, "answer": done()},
                    {"write": {"src/calc/__init__.py": FIXED}, "answer": done()}],
            "fix.review.root-cause-rosa": [PASS],
            "fix.review.principled-priya": [PASS],
            "siblings": [{"write": {"docs/debug/div-zero-17/siblings.md": "None.\n",
                                    "src/calc/test_regression.py": weakened}, "answer": done()},
                         {"write": {"docs/debug/div-zero-17/siblings.md": "None.\n"}, "answer": done()}],
            "siblings.review.root-cause-rosa": [PASS],
            "siblings.review.principled-priya": [PASS],
        })
        self.sign_off()
        state = self.the_run().state["tasks"]
        self.assertEqual([state[t]["attempts"] for t in ("fix", "siblings")], [2, 2])
        for tid in ("fix", "siblings"):
            with open(self.task_file(tid, "attempt-2", "feedback.md"), encoding="utf-8") as fh:
                told = fh.read()
            self.assertIn("src/calc/test_regression.py", told)
            self.assertIn("it is protected", told)
        path = "src/calc/test_regression.py"
        self.assertEqual(self.blob(state["reproduce"]["candidate"], path),
                         self.blob(state["fix"]["candidate"], path))
        self.assertEqual(self.blob(state["reproduce"]["candidate"], path),
                         self.blob(state["siblings"]["candidate"], path))
        self.check_invariants()


class Refactoring(TemplateRun):
    MODULE = 'def area(w, h):\n    return w * h\n\n\ndef perimeter(w, h):\n    return 2 * (w + h)\n'
    CHAR = ('import sys\nsys.path.insert(0, "src")\nimport shapes\n'
            'assert shapes.area(2, 3) == 6\nassert shapes.perimeter(2, 3) == 10\n')

    def test_three_steps_each_one_commit(self):
        """tpl: the refactoring template runs three chained steps, one commit each; a step over its
        diff budget, or one that breaks the characterisation tests, is sent back (TPL-14); the final
        panel sees the cumulative diff from characterise's commit: the three steps' changes and the
        report, and is told it spans from characterise (TPL-21)"""
        self.write("src/shapes/__init__.py", self.MODULE)
        self.generate("refactoring", {
            "name": "split-shapes", "brief": "briefs/split-pricing.md",
            "invariant": "area and perimeter return what they return today",
            "area": "src/shapes/**", "char_tests": "tests/characterisation/test_shapes.py",
            "test_char": "python3 -B tests/characterisation/test_shapes.py",
            "suite": "python3 -B tests/characterisation/test_shapes.py",
            "steps": ["Move area to area.py", "Move perimeter to perimeter.py", "Document the package"],
            "step_max_lines": 20,
        }, "split.toml")
        area = 'def area(w, h):\n    return w * h\n'
        perimeter = 'def perimeter(w, h):\n    return 2 * (w + h)\n'
        step1 = {"src/shapes/area.py": area,
                 "src/shapes/__init__.py": 'from .area import area\n\n\n' + perimeter}
        self.script({
            "characterise": [{"write": {"tests/characterisation/test_shapes.py": self.CHAR},
                              "answer": done()}],
            "characterise.review.meticulous-mira": [PASS],
            "characterise.review.principled-priya": [PASS],
            "characterise.review.steadfast-stefan": [PASS],
            "step-1": [{"write": dict(step1, **{"src/shapes/big.py": "x = 1\n" * 40}), "answer": done()},
                       {"write": step1, "remove": ["src/shapes/big.py"], "answer": done()}],
            "step-1.review.gatekeeper-gao": [PASS],
            "step-1.review.principled-priya": [PASS],
            "step-2": [{"write": {"src/shapes/perimeter.py": 'def perimeter(w, h):\n    return w + h\n',
                                  "src/shapes/__init__.py": 'from .area import area\nfrom .perimeter import perimeter\n'},
                        "answer": done()},
                       {"write": {"src/shapes/perimeter.py": perimeter}, "answer": done()}],
            "step-2.review.gatekeeper-gao": [PASS],
            "step-2.review.principled-priya": [PASS],
            "step-3": [{"write": {"src/shapes/__init__.py": '"""Shapes."""\nfrom .area import area\n'
                                                            'from .perimeter import perimeter\n'},
                        "answer": done()}],
            "step-3.review.gatekeeper-gao": [PASS],
            "step-3.review.principled-priya": [PASS],
            "final": [{"write": {"docs/refactor/split-shapes/final.md": "Three steps; surface unchanged.\n"},
                       "answer": done()}],
            "final.review.principled-priya": [PASS],
            "final.review.steadfast-stefan": [PASS],
        })
        self.sign_off()
        state = self.the_run().state["tasks"]
        self.assertEqual([state[t]["status"] for t in ("characterise", "step-1", "step-2", "step-3", "final")],
                         ["accepted"] * 5)
        self.assertEqual([state[t]["attempts"] for t in ("step-1", "step-2", "step-3")], [2, 2, 1])
        with open(self.task_file("step-1", "attempt-2", "feedback.md"), encoding="utf-8") as fh:
            self.assertIn("the change is larger than the task's diff budget", fh.read())
        with open(self.task_file("step-2", "attempt-2", "feedback.md"), encoding="utf-8") as fh:
            self.assertIn("python3 -B tests/characterisation/test_shapes.py", fh.read())
        commits = self.git_out("log", "--format=%H", "main..HEAD").split()
        self.assertEqual(len(commits), 5)              # characterise, three steps, final
        for tid in ("step-1", "step-2", "step-3"):
            self.assertIn(state[tid]["commit"], commits)
        self.assertEqual(len({state[t]["commit"] for t in ("step-1", "step-2", "step-3")}), 3)
        characterised = self.git_out("rev-parse", state["characterise"]["commit"] + "^{tree}")
        for rid in ("final.review.principled-priya", "final.review.steadfast-stefan"):
            with open(self.task_file(rid, "round-1", "diff.patch"), encoding="utf-8") as fh:
                patch = fh.read()
            for path in ("src/shapes/area.py", "src/shapes/perimeter.py", "src/shapes/__init__.py",
                         "docs/refactor/split-shapes/final.md"):
                self.assertIn("+++ b/" + path, patch)
            self.assertIn('+"""Shapes."""', patch)                      # step 3's change
            self.assertNotIn("tests/characterisation", patch)           # characterise's own work
            with open(self.task_file(rid, "round-1", "prompt.md"), encoding="utf-8") as fh:
                self.assertIn("This diff spans from 'characterise'", fh.read())
            verdict = self.read_json(rid, "round-1", "verdict.json")
            self.assertEqual(verdict["base"], characterised)
            self.assertEqual(verdict["diff_from"]["task"], "characterise")
        self.check_invariants()


if __name__ == "__main__":
    unittest.main()
